### ISSUE TITLE
Accent folding in search

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#1]

**Comment by bryvin** [comment]
The solution we discussed at the end of the stream was to use Regex to match the accented characters and also for the original filter.

However, I did get the majority of this working (minus the accented characters which would be really easy to add) and at this point it's already extremely slow with a good amount of notes. Not sure if it's worth doing that exactly how we discussed.

The other thing I noticed while testing was that for some reason typing in the Account window (bottom left) in the input fields.. that triggered the filtering to happen for each key pressed just as if you were typing in the search box. Not sure what that is about...

**Comment by mobitar** [comment]
Wait regular regex searching is extremely slow? Or are you referring to
your original solution?

On Oct 9, 2018, at 6:04 PM, Bryan <notifications@github.com> wrote:

The solution we discussed at the end of the stream was to use Regex to
match the accented characters and also for the original filter.

However, I did get the majority of this working (minus the accented
characters which would be really easy to add) and at this point it's
already extremely slow with a good amount of notes. Not sure if it's worth
doing that exactly how we discussed.

The other thing I noticed while testing was that for some reason typing in
the Account window (bottom left) in the input fields.. that triggered the
filtering to happen for each key pressed just as if you were typing in the
search box. Not sure what that is about...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/standardnotes/bounties/issues/1#issuecomment-428382672>,
or mute the thread

**Comment by bryvin** [comment]
The regex version is slow when you have to match for all words in the filter, in any order.. and that's before the accent check which I'm sure would add some time as well.

I found this benchmark someone created with the different methods of search and regex isn't always the fastest apparently.. http://jsben.ch/5qRcU

**Comment by mobitar** [comment]
Is it perceivably slower than the current production implementation?

On Oct 9, 2018, at 6:04 PM, Bryan <notifications@github.com> wrote:

The solution we discussed at the end of the stream was to use Regex to
match the accented characters and also for the original filter.

However, I did get the majority of this working (minus the accented
characters which would be really easy to add) and at this point it's
already extremely slow with a good amount of notes. Not sure if it's worth
doing that exactly how we discussed.

The other thing I noticed while testing was that for some reason typing in
the Account window (bottom left) in the input fields.. that triggered the
filtering to happen for each key pressed just as if you were typing in the
search box. Not sure what that is about...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/standardnotes/bounties/issues/1#issuecomment-428382672>,
or mute the thread

**Comment by bryvin** [comment]
Actually hang on.. I was debugging stuff at the same time and console.log seems to have had a really significant impact on performance. Let me do some further testing!

**Comment by bryvin** [comment]
Should this search exact words only? Or partial word matches too, but making sure to keep it so it has to match ALL filter words to show up.

Also it seems to be quick and working just fine currently.. until I open the console in Chrome. I assume its some sort of debug stuff thats happening there.. (nothing is being console logged anymore but still it slows down with console open). Fine otherwise.

**Comment by bryvin** [comment]
I have pushed to my pull request with what I have. It definitely feels just as fast when testing with the demo account notes (again until the console is open.. no clue why that happens). But this has accent folding and is still performing it seems. Definitely worth checking out at least if not merged to master.

It could also be sped up even more if the searching was timed out a little so it didn't happen on every key as you're typing but first waited for a slight pause (couple hundred ms). There seems to also be other things that are causing it to trigger the search/filtering which probably could be cleaned up.

**Comment by mobitar** [comment]
Closing as wontfix due to poor performance in regex implementation.
