### ISSUE TITLE
Mobile app export backup save to disk option

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#10]
Right now, when you click Export Backup in your mobile app Account/Settings page, it opens the default email browser and includes the backup file as an attachment. It would be great if instead it opened the native share dialog instead, where you can share that file to any app that supports receiving that file, which would include the email client anyway, but should also include saving to disk (particularly on Android).

Links:
- https://github.com/standardnotes/mobile

**Comment by jh-code** [comment]
After what I've been learning from working on the other bounty, I might as well take a stab at this one as well. :)

**Comment by mobitar** [comment]
Oh nice :)

**Comment by mobitar** [comment]
This is done in v3 mobile.
