### ISSUE TITLE
FileSafe attach file button can't be used again after error

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#11]
If there is an error with uploading file (you can probably simulate this with an offline connection), the Attach File button will not work again after that error. Requires restart of extension to work again.

Links:
- https://github.com/standardnotes/filesafe-client

**Comment by dagjaneiro** [comment]
Hmm...to address this issue seems like I would need access to `filesafe-embed` and I can't find the repo anywhere.

**Comment by mobitar** [comment]
Ah, sorry about that. Created these repos recently and was working on them in private mode before making public. Can be accessed here now: https://github.com/standardnotes/filesafe-embed

Although not sure if this issue still exists. Were you still able to replicate it?

**Comment by dagjaneiro** [comment]
Didn't have the chance to try it yet. Will let you know as soon as I get to it.

**Comment by dagjaneiro** [comment]
Couldn't replicate it. I added a fake WebDav integration to trigger an error when uploading the file and after the error, the button was working fine.

 I think you can close this.

**Comment by mobitar** [comment]
Ok great, thanks for confirming.
