### ISSUE TITLE
2FA Manager, option to Export Secret Key

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#12]
In the 2FA Manager, we recommend saving the secret in SN, but when setting up 2FA, you're temporarily restricted from accessing SN because the 2FA modal is blocking it. We want to add a "Export Secret" button during set up that will save the secret as a file whose contents are just the secret.

**Comment by dagjaneiro** [comment]
I've opened a PR to address this issue.

Here's an example of the UI with the button:

![image](https://user-images.githubusercontent.com/10207818/58373399-a2998b80-7f25-11e9-890d-f506b9f0a9df.png)

@mobitar, any suggestions on the style/positioning of the button?

**Comment by mobitar** [comment]
Nice! What about under the "Enable" button? Then, change Step 3 copy to:

"Save the **Secret Key** somewhere safe. You can export the Secret Key into a text file by choosing _Export Secret_."

**Comment by dagjaneiro** [comment]
This is how it's looking now based on your suggestions:

![image](https://user-images.githubusercontent.com/10207818/58387531-c9c88980-8007-11e9-8d52-6c75786591ef.png)

**Comment by mobitar** [comment]
Looks good! I'd say just make it so that the margin above the blue button matches the margin between the two buttons.

**Comment by dagjaneiro** [comment]
Will do!

**Comment by dagjaneiro** [comment]
Which one do you prefer:

1. padding between buttons matches padding top
![image](https://user-images.githubusercontent.com/10207818/58436089-8e879280-80bb-11e9-8ba0-f87462b250c1.png)

2. padding top matches padding between buttons
![image](https://user-images.githubusercontent.com/10207818/58436119-a9f29d80-80bb-11e9-938b-a14a4d2e5b3c.png)

I have the first version in the PR. Let me know If you want me to change it to the second version.

**Comment by mobitar** [comment]
Yup, first one 👍 I'll take a look at this some time this week hopefully.
