### ISSUE TITLE
Simple Markdown Editor code highlighting inconsistencies

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#17]
https://github.com/sn-extensions/simple-markdown-editor/issues/11

**Comment by dagjaneiro** [comment]
Hey, Mo!

From the initial discussion it seems you want to:
1. Allow syntax highlight when the syntax __```language__ has spaces after it
2. Enable auto syntax highlight if no language is specific (btw I couldn't make it work in the current version even after adding one space as you suggested)

Is there something else you had in mind for this issue?

**Comment by mobitar** [comment]
Hey Daniel, I believe those were the only two issues, in that the syntax requirements were very strict. Testing now, the behavior I see is that three backticks followed by the language with no space will generate the correct syntax highlighting. Adding a space removes highlighting. This might be hard to fix though, as it's handled by the underlying Markdown engine. So our only hope is if there's some sort of option we can pass into the engine.
