### ISSUE TITLE
Simple Markdown Editor three buttons on bottom are out of reach on some mobile devices

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#19]
![simulator screen shot - iphone 8 - 2018-11-29 at 13 04 54](https://user-images.githubusercontent.com/3277844/49245246-66063080-f3d7-11e8-88ba-09df984f44c1.png)

The three buttons on the bottom that say "Edit|Split|Preview" are cutting off on this iPhone 8. Doesn't cut off on iPhone X. However, on iPhone X, it's hard to interact with because it's all the way at the bottom.

One part of the solution will be to just move the three buttons to the top of the editor rather than the bottom.

After that however, we want to make sure the content size is still not being cut off from the bottom. So better to fix the content size issue first, then move the buttons to the top.

Related bounties:
- https://github.com/standardnotes/bounties/issues/17

**Comment by bryvin** [comment]
Will the idea be to move those 3 buttons for all versions of the editor (desktop, web and mobile) or just on mobile?

I'd have to look to see, but I believe the note's title is always the first visible text field at the top. Would those buttons just go underneath that.. I think that would be the only location they could go?

**Comment by mobitar** [comment]
All versions. Like the Fancy Markdown Editor. I think we also make the menu bar take up less vertical space. Maybe reduced by 5px..

**Comment by mobitar** [comment]
Working on this now. Haven't tested mobile yet. https://github.com/sn-extensions/simple-markdown-editor/commit/bbf8dc2e1786c6849bd3310f544bebd1372f7193
