### ISSUE TITLE
Simple Markdown Editor, make both columns same size on default load

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#25]
<img width="849" alt="Screen Shot 2019-05-26 at 11 25 25 AM" src="https://user-images.githubusercontent.com/3277844/58384796-28f8b080-7fac-11e9-826e-8e27464f4ee5.png">

Right column seems to fit two extra words on first line, so overall, with no formatting, the left and right will not be in sync.

**Comment by dagjaneiro** [comment]
I've tackled this issue and made some additional changes to the size of the buttons, let me know what you think.
