### ISSUE TITLE
Simple Task Editor sort gesture on mobile

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#26]
The Simple Task Editor supports drag and dropping a task to re-order (drag by the checkbox). However on mobile we disable this as it interferes with scrolling, and I haven't explored a workaround. I've seen this gesture work properly before on mobile on other websites, so I'm sure there's a solution here.

**Comment by dagjaneiro** [comment]
I have some ideas on how to tackle this. Will try to get some work done on it today.

**Comment by dagjaneiro** [comment]
I've uploaded of gif of the editor on iOS in the PR, can you take a look at it and let me know if that's what you wanted?

**Comment by mobitar** [comment]
I'm not seeing any gifs on the PR? https://github.com/sn-extensions/simple-task-editor/pull/17

**Comment by dagjaneiro** [comment]
Strange...maybe I forgot to save when editing... well it's there now.
