### ISSUE TITLE
Windows/Linux minimize to tray

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#27]
https://github.com/standardnotes/desktop/issues/103

I did some work on this previously but did not complete it, for reasons I don't recall: https://github.com/standardnotes/desktop/commit/ce51cfdebf2952bb18a24c3b660ad91cab237d89

I can't find the issue reference anymore, but someone mentioned this was also common on Linux.

**Comment by dagjaneiro** [comment]
Lots of requests on this one, I will start working on it tomorrow.

**Comment by dagjaneiro** [comment]
What're your thoughts on the global shortcut? 

Do you also want to implement it? How should we go about providing a way to configure it?

**Comment by mobitar** [comment]
> What're your thoughts on the global shortcut? Do you also want to implement it?

No, just the minimize to tray part.

**Comment by dagjaneiro** [comment]
I think this one's done. Take a look at it and see if you're happy with the functionality.

**Comment by mobitar** [comment]
Nice work! I'm gearing up to release 3.0.10, and have frozen its scope. So I'll test out this functionality after this release.
