### ISSUE TITLE
Improve spellcheck performance on desktop

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#28]
There's something about our spellcheck implementation that causes performance reductions when using, in the plain editor. You can replicate this by typing out a really long note, and noticing the differences in typing lag with spellcheck enabled and disabled (you can toggle spellcheck from the Options menu in the editor panel).

I believe we use the same spellcheck engine and module that Atom uses, so not sure why our implementation has this characteristic.

This is the spellcheck package we're using: https://github.com/mobitar/node-spellchecker. I forked it to provide Linux prebuilds, if I recall correctly.

**Comment by dagjaneiro** [comment]
Will tackle this one next. Is this feature also available on mobile?

**Comment by mobitar** [comment]
We don't do any custom work regarding spellcheck on mobile. Just whatever the system offers.
