### ISSUE TITLE
Remember preview state in Advanced Markdown Editor

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#31]
We want the Advanced Markdown Editor to remember its preview state per note. The editor by default starts in edit mode. There are two other modes: preview (the eye icon) and side-by-side (the split panel icon). 

When you make a selection here, it should persist this value and save it on a per note basis, so that when you come back to the note, it goes immediately back to the remembered state. To do so, you would use `note.clientData` to save the preference. Check out the [Code Editor source](https://github.com/sn-extensions/code-editor/blob/master/src/main.js#L52) for an example, which saves the programming language preference on a per-note basis.

**Comment by dagjaneiro** [comment]
Have a solution for this one in https://github.com/sn-extensions/advanced-markdown-editor/pull/16.
