### ISSUE TITLE
Add AWS S3 as a FileSafe relay option

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#32]
The [relay server](https://github.com/standardnotes/filesafe-relay) for FileSafe ([filesafe.standardnotes.org](filesafe.standardnotes.org)) is a simple stateless Rails based server that handles communicating with a cloud provider.

The relay currently supports Dropbox, Google Drive, and WebDAV. The goal of this bounty is to add S3 as an option via the [aws-sdk gem](https://github.com/aws/aws-sdk-ruby).

Integrations are abstracted, so it should be pretty easy to add a new one. See the current directory of integrations here:

https://github.com/standardnotes/filesafe-relay/tree/master/app/lib/integrations

The integration class you write will need to implement these functions:
-  def initialize(params = {})
- def type (options are presently `oauth` and `form`, but you may declare a new type of `aws-s3` and handle that type [as needed](https://github.com/standardnotes/filesafe-relay/blob/master/app/controllers/integrations_controller.rb#L6)
- def save_item(params)
- def download_item(metadata = {})
- def delete_item(metadata)

You will add the S3 button here: https://github.com/standardnotes/filesafe-relay/blob/master/app/views/application/index.html.haml and likely need to create a page [similar to this](https://github.com/standardnotes/filesafe-relay/blob/master/app/views/integrations/link.html.haml) to fill in whatever AWS credentials are required.

The required credentials by AWS should be such that a user can create a dedicated user key and secret for use with FileSafe. I believe that should just be the standard behavior of user accounts with AWS.

**Comment by dagjaneiro** [comment]
I'll start working on this one next.

**Comment by dagjaneiro** [comment]
I've opened a [PR](https://github.com/standardnotes/filesafe-relay/pull/2) to tackle this, please let me know what you think.

**Comment by mobitar** [comment]
I've left a comment [inline](https://github.com/standardnotes/filesafe-relay/pull/2#discussion_r294805041) regarding updating global state.
