### ISSUE TITLE
Spreadsheets editor can't scroll on Android

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#34]
Works fine on desktop and iOS, but on Android, I'm getting reports that the sheet is not scrollable/pannable at all. Might just be the viewport meta tag.

**Comment by dagjaneiro** [comment]
This is a known bug in the library: https://github.com/telerik/kendo-ui-core/issues/2929. It looks like it was fixed in the latest release (2019.R2.SP1). 

I won't be able to test it myself since I don't have access to the Kendo UI bundle.

**Comment by dagjaneiro** [comment]
I can confirm the issue as been fixed. I've opened a PR that upgrades the lib using a custom build to the latest stable version.
