### ISSUE TITLE
Windows app cannot handle file:\\ links from Bold Editor

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#35]
https://github.com/standardnotes/forum/issues/568#issuecomment-508270334

Works on macOS.

**Comment by dagjaneiro** [comment]
I'll be looking into this one next as it seems to be affecting more customers.

**Comment by dagjaneiro** [comment]
What's the desired behaviour here? Should it download the file or try to open it in a new tab?

**Comment by mobitar** [comment]
It should just open the file in the default system viewer for that file type.

**Comment by dagjaneiro** [comment]
Opened a PR to address this issue and left a couple of suggestions that could potentially prevent any security concerns.

**Comment by aaantoszek** [comment]
So it **should** work! Damn, this is really important to me
