### ISSUE TITLE
Mobile React Native: Don't show unsupported themes

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#41]
https://github.com/standardnotes/mobile/issues/180

**Comment by bryvin** [comment]
I did some digging and see there is code in here that sets dimmed to [theme.getNotAvailOnMobile()](https://github.com/standardnotes/mobile/blob/master/src/screens/SideMenu/MainSideMenu.js#L129). I don't believe this is actually utilized though in the code anymore, it's passed down to the Cell here: https://github.com/standardnotes/mobile/blob/master/src/screens/SideMenu/SideMenuSection.js#L53 but the Cell doesn't utilize it: https://github.com/standardnotes/mobile/blob/master/src/screens/SideMenu/SideMenuCell.js

I also noticed you had a check in [StyleKit.js](https://github.com/standardnotes/mobile/blob/master/src/style/StyleKit.js#L294) that was verifying if it was a mobile allowed theme solely based on if it has "variables" or not. However, I logged out the data from the themes in question (No Distraction, etc) and they **do** have variables so this is likely why it's not working now. 

Is there any other information I am missing here that is set on the themes that shouldn't work on mobile? If not maybe there should be some extra info in the config for the extension/theme?

**Comment by mobitar** [comment]
Hmm..no distraction doesn't have variables. However, this is probably not a scaleable way to check for mobile support. Better to introduce an extra config variable as you suggested.

I was initially thinking we can do it inside of package.json for each theme, but I don't think the mobile app has access to that. It just downloads the css file directly. So what if we introduced a CSS variable:

`--sn-stylekit-theme-no-mobile = true`

I'm not sure if `true` is allowed in a CSS variable. But if not, we can just use another valid value, maybe 0/1.

Would this solution work based on your testing?

**Comment by bryvin** [comment]
Yeah I think that may actually work, otherwise the only thing that calls setNotAvailOnMobile from what I can tell is if it doesn't have a hosted_url or a url set when trying to download.

It also already parses the CSS file so I'm sure it'd be pretty easy to add that in to check for that variable.

**Comment by bryvin** [comment]
Actually, I just checked and [onThemeSelect](https://github.com/standardnotes/mobile/blob/master/src/screens/SideMenu/MainSideMenu.js#L82) does have access to the theme which you can do theme.content.package_info. So an additional value could be added here prevent use on mobile, maybe something like disallow_mobile: true

Also, either way this would still be broken until the cached versions were cleared I believe.
