### ISSUE TITLE
Listed: Links to anchors on the same page should open in the same tab?

### ISSUE THREAD

**Issue by seanakabry** [standardnotes/bounties#47]
Listed seems to add `target="_blank"` to every link in a post, regardless of whether the link was written in Markdown or HTML. This behaviour seems undesirable when linking to anchors on the same page, and particularly in the case of MultiMarkdown footnotes, which Listed supports.

Would it be possible for `target="_blank"` to be added only to links pointing somewhere other than the active page?

**Comment by mobitar** [comment]
👍

**Comment by johnny243** [comment]
I'd like to work on it this week. Let me know!

**Comment by mobitar** [comment]
Go for it!

**Comment by mobitar** [comment]
Closed via https://github.com/standardnotes/listed/pull/14
