### ISSUE TITLE
Listed: ability to delete blog directly from Settings page

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#48]
Should have an option that says "Delete Blog". Should then present confirmation (we don't want to use JS `confirm` as the default prompts on this ("OK" and "Cancel") are confusing).

"Are you sure you want to permanently delete your Listed blog and all associated posts. Note that this will not affect any of the source notes in your Standard Notes account."

Upon deletion we should delete their Author model, all Posts, Domain, Credentials, Tips, GuestbookEntries, Subscribers, and Subscriptions.

https://github.com/standardnotes/listed

**Comment by johnny243** [comment]
This is great, I'd like to work on this feature.

**Comment by mobitar** [comment]
Go for it 👍
