### ISSUE TITLE
Scrollbars on Windows desktop/web

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#6]
Scrollbars on Windows do not look great, especially with extensions. We have custom scroll bar styles for Windows, but they only appear on hover, and shift the content from the right side of the panel.

The solution would be either to:
a. Make it so that scrollbars on hover do not shift content from the right
b. Display scrollbars at all times, even when not interacting with that column (not ideal)
c. ???

Solution probably involves:

- Extract scrollbar styles from https://github.com/standardnotes/web/blob/master/app/assets/stylesheets/app/_scrollbars.scss to [StyleKit](https://github.com/sn-extensions/StyleKit).

- Remove on hover overflow "hack": https://github.com/standardnotes/web/blob/master/app/assets/stylesheets/app/_notes.scss#L90
https://github.com/standardnotes/web/blob/master/app/assets/stylesheets/app/_tags.scss#L42

**Comment by ViableClanMember** [comment]
I halped :P `overflow:overlay;`

**Comment by mobitar** [comment]
@ViableClanMember haha, come on stream, we'll hook you up with some Extended :)
